### ISSUE TITLE
LLM Usecases

### ISSUE THREAD

**Issue by BabarKhanDev** [2023-gpig-a/LLM#1]

**Comment by BabarKhanDev** [comment]
What makes it so that we need to use an LLM, what does an LLM in particularly offer us that no other solution does?

**Comment by cjd552** [comment]
Better to be done after interview hence blocked by 2023-gpig-a/issues#20 and 2023-gpig-a/issues#17

**Comment by cjd552** [comment]
wrote about this in the report draft which currently lives in https://docs.google.com/document/d/1Tp_a0k9w5qBH2J0Ga63FclvVG4NnPh0Dz8pBtN02mQk/edit and will transfer into the overleaf
